updated @velas/staking.2.0 to v1.1.0, feature/VLWA-1778
velas/web-wallet pull request #611
Opened 2022-06-29 11:26 UTC by dmitrii602

2022-06-29 11:28 UTC, FrozenPyrozen approved these changes

2022-06-29 11:30 UTC, Apindes approved these changes

2022-07-01 11:44 UTC, olexandr13 requested changes

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/screens/staking-2.ts
> +      await this.page.locator('#address-validator', {hasText: validatorAddress}).click();
`await this.page.locator('#address-validator', { hasText: validatorAddress }).click();`

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/screens/staking-2.ts
> +    loader: this.page.locator('.item.blink').first(),
попробуй написать локатор однозначнее, без first. потому что непонятно какой будет first, этот или другой. потенциально могут быть проблемки от этого

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/screens/staking-2.ts
> +      const currentValidator = await this.validator.copyAddress();
в действии на reaload не должно быть copy address

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/screens/staking-2.ts
> +      await this.validatorsList.reload();
там же отдельная кнопка на релоад инфы конкретного стейка/валидатора
а ты рефрешишь все. это норм?

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/test-data.ts
> +      staker2_1_old:{
а почему пришлось создать новый акк?

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/tests/manual-run/bridges.received.test.ts
> +    for (let [key, value] of Object.entries(balances)) {
намудрил ты с entries
```

    for (let tokenName in balances) {
      const token = tokenName as Currency;
      if (token === 'token-vlx_evm' && Number(balances[token]) < 0.000007){
        throw new Error (`Balance of ${token} is ${balances[token]}, 0.000007 expected`)
      }
      if (token !== 'token-vlx_evm' && tokens.includes(token as Currency) && Number(balances[token]) === 0){
        throw new Error (`Balance of ${token} is zero`)
      }
    }
```

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/tests/manual-run/bridges.received.test.ts
> +  test('check balances', async ({ wallets }) => {
check balances are not zero

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/tests/manual-run/bridges.send.test.ts
> +test.describe('Bridge test 1:', () => {
почему не `beforeAll'?

2022-07-01 11:44 UTC, olexandr13 commented on e2e/src/tests/stable/wallets.test.ts
> +      // TODO: need to scroll to launch test for mainnet
в playwright есть метод `.scrollIntoViewIfNeeded();`

2022-07-01 15:29 UTC, Corresponsible commented on e2e/src/screens/staking-2.ts
> +      await this.validatorsList.reload();
comment

2022-07-01 16:08 UTC, olexandr13 approved these changes

2022-07-01 16:24 UTC, Corresponsible approved these changes

2022-07-01 16:25 UTC, merged